# $FreeBSD$

MDSRCS+= \
	bcopy.c \
	bcopy.S \
	bcopy_vsx.S \
	memcpy.c \
	memcpy.S \
	memcpy_vsx.S \
	memmove.c \
	strcpy_arch_2_05.S \
	strcpy.c \
	strcpy_resolver.c \
	strncpy_arch_2_05.S \
	strncpy.c \
	strncpy_resolver.c
